### PR TITLE
85 create a widget for all textformfields

### PR DESCRIPTION
**Pull request by SeitansPilgrim**
I created a new widget that is similar to `TextInputWidget` but more suitable for user input fields (register form, login etc.). 

This widget takes in a validator and has an errorBorder. That makes it possible to have nice looking real time validation. See login implementation for validator implementation.

Goal is to use this widget, `UserInput`,  insted of `TextInputWidget` for all user forms.

### CODE REVIEW

**Review by Magoulo — APPROVED** [review]
nice!

**Review by willemannen — APPROVED** [review]
Looks good

**Review by Melesab — APPROVED** [review]
Verkar jätte fint, bra jobbat med validator

**Review by ThorinEk — APPROVED** [review]
Ser bra ut! Perfekt att vi nu har en sådan här Widget som kan återanvändas mycket nu!

**Pull request merged**
